// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  list: dynamic(() => import("./List")),
  paragraph: dynamic(() => import("./Paragraph")),
  slider: dynamic(() => import("./Slider")),
  title: dynamic(() => import("./Title")),
};
