import './globals.css'

import { Almarai } from 'next/font/google'
const almarai = Almarai({ subsets: ['arabic'], weight: '400' })

export const metadata = {
  title: 'Corporate Agency Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${almarai.className} bg-light-400 dark:bg-dark-400`}>
        <main>{children}</main>
      </body>
    </html>
  )
}
