import './globals.css'

import { Almarai } from 'next/font/google'
const almarai = Almarai({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Corporate Agency Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={almarai.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}
